### ISSUE TITLE
I couldn't run the script because data is not enough

### ISSUE THREAD

**Issue by dedeco** [shabbychef/bogbt#1]
Please, Can you share the raw data or the processed data used? I'm trying to do a reproducibility from a research and I like very much of your article. Thanks in advance!

**Comment by shabbychef** [comment]
The tweets cannot in any way be shared due to the data license. The user IDs can be shared, as I understand it, but I cannot dig them up at this moment. Some of this data may be available via kaggle now or in the near future, I believe.

**Comment by dedeco** [comment]
@shabbychef OK. Thanks. And the processed data or cleaned? Your research and your approach
interest me a lot. Please, when possible or you up to haggle let me know.
